# Generated by Django 4.1.7 on 2023-04-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Url",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_link", models.URLField()),
                (
                    "shortened_link",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Url",
                "verbose_name_plural": "Urls",
            },
        ),
    ]
